//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entrhopi.Guild_Missions.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("entrhopi.Guild_Missions.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string gmButtonClearAll {
            get {
                return ResourceManager.GetString("gmButtonClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string gmButtonExport {
            get {
                return ResourceManager.GetString("gmButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string gmButtonImport {
            get {
                return ResourceManager.GetString("gmButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy everything to Clipboard.
        /// </summary>
        internal static string gmButtonSendToChat {
            get {
                return ResourceManager.GetString("gmButtonSendToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wiki.
        /// </summary>
        internal static string gmButtonWiki {
            get {
                return ResourceManager.GetString("gmButtonWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read or wirte to clipboard. Please try again..
        /// </summary>
        internal static string gmNotificationClipboardError {
            get {
                return ResourceManager.GetString("gmNotificationClipboardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} waypoints from clipboard!.
        /// </summary>
        internal static string gmNotificationClipboardRead {
            get {
                return ResourceManager.GetString("gmNotificationClipboardRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0} waypoints to clipboard!.
        /// </summary>
        internal static string gmNotificationClipboardSaved {
            get {
                return ResourceManager.GetString("gmNotificationClipboardSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string gmPanelInfo {
            get {
                return ResourceManager.GetString("gmPanelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string gmPanelList {
            get {
                return ResourceManager.GetString("gmPanelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Treks.
        /// </summary>
        internal static string gmPanelSavedTreks {
            get {
                return ResourceManager.GetString("gmPanelSavedTreks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string gmPanelSearchResults {
            get {
                return ResourceManager.GetString("gmPanelSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name here ....
        /// </summary>
        internal static string gmSearchPlaceholder {
            get {
                return ResourceManager.GetString("gmSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Missions.
        /// </summary>
        internal static string gmTabName {
            get {
                return ResourceManager.GetString("gmTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounty.
        /// </summary>
        internal static string gmTypeBounty {
            get {
                return ResourceManager.GetString("gmTypeBounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        internal static string gmTypeChallenge {
            get {
                return ResourceManager.GetString("gmTypeChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle.
        /// </summary>
        internal static string gmTypePuzzle {
            get {
                return ResourceManager.GetString("gmTypePuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string gmTypeRace {
            get {
                return ResourceManager.GetString("gmTypeRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Guild Mission Type.
        /// </summary>
        internal static string gmTypeSelect {
            get {
                return ResourceManager.GetString("gmTypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trek.
        /// </summary>
        internal static string gmTypeTrek {
            get {
                return ResourceManager.GetString("gmTypeTrek", resourceCulture);
            }
        }
    }
}
